sky:
  redis:
    host: localhost
    port: 6379
    password: 20030503_Zrd
    database: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root
  wechat:
    appid: wxe5c17d39ac67d23b
    secret: 467ad623342de7262e58f51a94a94bed
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\pay\apiclient_key.pem
    apiV3Key: CZBK51236435wxраy435434323FFDuv3
    weChatPayCertFilePath: D:\pay\wechatpy.pem
    notifyUrl: http://localhost:8080
    refundNotifyUrl: http://localhost:8080/notify/refundSuccess
  minio:
    endpoint: http://127.0.0.1:9000
    access-key: minioadmin
    secret-key: minioadmin
    bucket-name: sky-take-out
    public-endpoint: http://127.0.0.1:9000